github: `actions/setup-microceph`
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/.github/actions/setup-microceph/action.yml b/.github/actions/setup-microceph/action.yml
--- a/.github/actions/setup-microceph/action.yml
+++ b/.github/actions/setup-microceph/action.yml
@@ -18,9 +18,31 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Ephemeral disk checks
+      shell: bash
+      run: |
+          set -eux
+
+          # If the rootfs and the ephemeral part are on the same physical disk, giving the whole
+          # disk to microceph would wipe our rootfs. Since it is pretty rare for GitHub Action
+          # runners to have a single disk, we immediately bail rather than trying to gracefully
+          # handle it. Once snapd releases with https://github.com/snapcore/snapd/pull/13150,
+          # we will be able to stop worrying about that special case.
+          if [ "$(stat -c '%d' /)" = "$(stat -c '%d' /mnt)" ]; then
+            echo "FAIL: rootfs and ephemeral part on the same disk, aborting"
+            exit 1
+          fi
+
     - name: Free-up ephemeral disk
+      shell: bash
       id: free_ephemeral_disk
-      uses: ./.github/actions/free-ephemeral-disk
+      run: |
+          set -eux
+
+          sudo swapoff /mnt/swapfile
+          ephemeral_disk="$(findmnt --noheadings --output SOURCE --target /mnt | sed 's/[0-9]\+$//')"
+          sudo umount /mnt
+          echo "ephemeral_disk=${ephemeral_disk}" >> "${GITHUB_OUTPUT}"
 
     - name: Install MicroCeph snap
       shell: bash
